# Generated by Django 5.1 on 2024-08-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contact',
            new_name='contract',
        ),
    ]
