# Generated by Django 5.1 on 2024-08-20 03:44

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_rename_contact_contract_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'permissions': (('import_folder', 'Can import contract'), ('export_folder', 'Can export contract')), 'verbose_name': 'contract'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract',
            field=models.ImageField(upload_to=contract.models.customers_contract, verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mtime',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
